# Generated by Django 3.0.8 on 2020-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('std_id', models.BigIntegerField()),
                ('department', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.BigIntegerField()),
                ('dateofjoin', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
