# Generated by Django 3.0.8 on 2020-10-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
