# Generated by Django 3.0.8 on 2020-09-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='std_id',
            new_name='stf',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_id',
            new_name='std',
        ),
    ]
