# Generated by Django 3.0.8 on 2020-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.BigIntegerField(),
        ),
    ]
