# Generated by Django 3.0.8 on 2020-09-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200922_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='stf',
            new_name='usr',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std',
            new_name='usr',
        ),
    ]
