# Generated by Django 3.0.8 on 2020-09-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('std_id', models.BigIntegerField()),
                ('department', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.BigIntegerField()),
                ('dateofjoin', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('sectionincharge', models.CharField(default='no', max_length=20)),
            ],
        ),
    ]
