# Generated by Django 3.0.8 on 2020-10-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201004_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
