# Generated by Django 3.0.8 on 2020-09-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='std_id',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
    ]
