# Generated by Django 3.0.8 on 2020-10-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201006_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookfilename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
