# Generated by Django 3.0.8 on 2020-09-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200918_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='std_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
    ]
