# Generated by Django 3.0.8 on 2020-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201006_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
