# Generated by Django 3.0.8 on 2020-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(default='disabled', max_length=50),
        ),
    ]
