# Generated by Django 3.0.8 on 2020-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='result',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
