# Generated by Django 3.0.8 on 2020-10-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_result_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
