# Generated by Django 3.0.8 on 2020-11-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_batch_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
                ('semester', models.BigIntegerField()),
                ('batch', models.CharField(max_length=20)),
                ('sem1fee', models.BigIntegerField(default=0)),
                ('sem2fee', models.BigIntegerField(default=0)),
                ('sem3fee', models.BigIntegerField(default=0)),
                ('sem4fee', models.BigIntegerField(default=0)),
                ('sem5fee', models.BigIntegerField(default=0)),
                ('sem6fee', models.BigIntegerField(default=0)),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
        ),
    ]
