# Generated by Django 3.0.8 on 2020-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_fess'),
    ]

    operations = [
        migrations.AddField(
            model_name='fess',
            name='sem1paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fess',
            name='sem2paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fess',
            name='sem3paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fess',
            name='sem4paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fess',
            name='sem5paid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fess',
            name='sem6paid',
            field=models.BigIntegerField(default=0),
        ),
    ]
