# Generated by Django 3.0.8 on 2020-11-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201114_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='semtotal',
            field=models.BigIntegerField(default=25000),
        ),
    ]
