# Generated by Django 3.0.8 on 2020-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fees_semtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='sem1fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem2fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem3fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem4fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem5fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='sem6fee',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='semtotal',
        ),
        migrations.AddField(
            model_name='fees',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
